include:
  - ./elastic-search-docker-compose.yml
  
  
services:
    mongo-es-indexer:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mongo_es_indexer
        command: ['yarn', 'start:debug']

networks:
    default:
        driver: bridge
